name: Deploy

on:
  push:
    branches: [main]
    tags: ['*']

env:
  BACKEND_NAME: computer-club-backend
  FRONTEND_NAME: computer-club-frontend
  BACKEND_URL: 'https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com'

jobs:
  Backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build backend
        run: |
          chmod +x ./scripts/build_backend.sh
          ./scripts/build_backend.sh
      - name: Deploy backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: 'backend'
          stack: 'heroku-22'
          region: 'eu'
          procfile: 'web: npm run start:prod'
          healthcheck: '${{ env.BACKEND_URL }}/test'
          rollbackonhealthcheckfailed: true

  Frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set project env vars
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: ${{ env.FRONTEND_NAME }}
          envVariableKeys: NEXT_PUBLIC_BACKEND_URL
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ env.BACKEND_URL }}
          TARGET_NEXT_PUBLIC_BACKEND_URL: production,preview,development
          TYPE_NEXT_PUBLIC_BACKEND_URL: plain
      - name: Deploy frontend
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod --yes'
          vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend

  Release:
    runs-on: ubuntu-latest
    needs: [Backend, Frontend]

    steps:
      - name: Get git tag
        uses: olegtarasov/get-tag@v2.1
      - name: Create release
        if: ${{ env.GIT_TAG_NAME != '' }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ env.GIT_TAG_NAME }}'
          prerelease: false
